### ISSUE TITLE
Level - Level1

### ISSUE THREAD

**Issue by pwun** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#16]
Als Spieler möchte ich Level absolvieren um der Hauptaufgabe, der Flucht aus der Kanalisation, näher zu kommen.

**Comment by magnimma** [comment]
Man kann mittels klick auf Button, ein Gitter öffnen, welches ein mögliches Areal für ein erstes Level eröffnen lässt.

**Comment by pwun** [comment]
level mit ein und Ausgang zum hauptareal, Glasscherben als Hindernisse, keine Gegner, reiner jump&run level für den leichten spieleinstieg

**Comment by IgorSomik** [comment]
Ein Bereich in dem sich Säure befindet. Bei Berührung mit der Säure fängt der Spieler erneut am Anfang des Levels an.
