### ISSUE TITLE
Steuerung - Tastaturbelegung

### ISSUE THREAD

**Issue by pwun** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#18]
Als Spieler möchte ich eine intuitive Steuerung, um meinen Charakter zu bewegen.

**Comment by magnimma** [comment]
-first person view auf "v" wie "view" gelegt
-mit maus nach rechts/links drehen
-mit maus in first person nach oben/unten möglich
-mit W/S vor und zurück
-mit A/D seitwärts nach links und rechts
