### ISSUE TITLE
Story - Einführung in die Geschichte

### ISSUE THREAD

**Issue by pwun** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#21]
Als Spieler möchte ich in die Geschichte eingeführt werden und wissen was vor Story beginn passiert ist.

**Comment by pwun** [comment]
Eine Geschichte ist angelegt, muss aber noch in das Projekt implementiert werden

**Comment by amyLie** [comment]
Oh nein, die neugierige Wanderratte hat sich in die Kanalisation verirrt!! Hier gefällt es ihr überhaupt nicht und Hunger hat sie auch. Hilf ihr einen Weg aus dem Kanal zu finden, doch gib Acht auf Gefahren, die hier lauern könnten. Vielleicht kann dir die Ratte auf der anderen Kanalseite nützliche Tips geben...

**Comment by krisk1** [comment]
In das game eingebaut
