### ISSUE TITLE
Grafik - Einheitsgröße für Weltobjekte

### ISSUE THREAD

**Issue by amyLie** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#27]
als Leveldesigner möchte ich mit einheitlichen Objekten arbeiten

**Comment by IgorSomik** [comment]
95% der Weltobjekte wurden auf Einheitsgröße gebracht.

**Comment by IgorSomik** [comment]
Alle bis jetzt vorhandenen Weltobjekte sind nun auf Einheitlich!
