### ISSUE TITLE
Level - Texturen hinzufügen

### ISSUE THREAD

**Issue by amyLie** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#28]
Als Spieler möchte ich eine ansprechende Farbgestaltung der Spielwelt haben

**Comment by pwun** [comment]
UV Maps erstellt und  erste Texturen angelegt, allerdings noch nicht eingefügt

**Comment by pwun** [comment]
Textur für Boden/ Decke

**Comment by pwun** [comment]
Textur für Kanalsysteme

**Comment by pwun** [comment]
Alle relevanten Texturen wurden erstellt und ins Spiel eingefügt
