### ISSUE TITLE
Level - Gegner

### ISSUE THREAD

**Issue by magnimma** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#34]
Der Spieler möchte eine Herausforderung im Spiel und deswegen auf Gegner im Spiel treffen.

**Comment by pwun** [comment]
Gegner folgen dem Spieler, können nicht mehr ineinander laufen und haben Schwerkraft

**Comment by magnimma** [comment]
Gegner funktionieren größtenteils. empfangen Koliisionen und reagieren auf Spieler
