### ISSUE TITLE
Code - Zwischenspeicher zwischen einzelnen Levelabschnitten

### ISSUE THREAD

**Issue by pwun** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#38]
Als Spieler möchte ich nicht das ganze Level erneut durchlaufen wenn ich in einem späteren Abschnitt sterbe

**Comment by krisk1** [comment]
Done!
Aktuell drei Checkpoints.
Auch die Richtung in die der Spieler beim Respawnen schauen soll wird berücksichtigt.
