### ISSUE TITLE
Level - Kanalisationssysteme auf einheitliche Koordinaten setzen

### ISSUE THREAD

**Issue by IgorSomik** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#44]
Als Spieler möchte ich in das nächste Level durch die Kanalisation gelangen.

**Comment by IgorSomik** [comment]
Kanalisationssystem zwischen Ausgangslevel und Level 1 wurde auf einheitliche Koordinaten gebracht.

**Comment by pwun** [comment]
Alles auf einheitlichen Koordinaten bis auf die Kanalbiegung

**Comment by IgorSomik** [comment]
Alle Assets haben eine einheitliche Größe.
