### ISSUE TITLE
Level - Level 2

### ISSUE THREAD

**Issue by IgorSomik** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#49]
Als Spieler möchte ich nach Level 1 weitere Level absolvieren um der Flucht aus der Kanalisation näher zu kommen

**Comment by IgorSomik** [comment]
Kanalisation zu Level 2 wurde Angelegt.
Level 2 wurde erstellt und die grobe Mechanik ist vorhanden.

**Comment by magnimma** [comment]
Lichtschalter-Rätsel programmiert.
