### ISSUE TITLE
Grafik - UV Mapping

### ISSUE THREAD

**Issue by amyLie** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#50]
Als Grafiker brauche ich UV Maps um Texturen erstellen zu können

**Comment by pwun** [comment]
UV Maps für Boden/ Decke

**Comment by pwun** [comment]
UV Maps für Kanalsysteme

**Comment by pwun** [comment]
Alle relevanten Objekte wurden UV gemapped
