### ISSUE TITLE
Als Spieler möchte ein Bugfreies Spielerlebnis

### ISSUE THREAD

**Issue by krisk1** [PSMGGamesSS2015/PSMG_SS_2015_Rats_Canalisation#58]

**Comment by krisk1** [comment]
- Checkpoint working now properly
- ShowLevel1CAmera now disabled bydefault
- changed executionorder of scripts. Gates open now after camera switches
- Rat Animations now smoother / less delay
- Camera can no longer be activated at all times after first regular activation
- Now properly switches cameras after showing any of the level camera
  overviews
- Rat no longer is able to keep running when last cheese decays
- UI now better scales with different screen sizes
- Fixed Responsiveness of PauseMenu Buttons

**Comment by krisk1** [comment]
- Camera behind the Rat now smoother and does not show that much of the outside of the world anymore

**Comment by krisk1** [comment]
- Wackeltreppe no longer slides down
- Rat cant move anymore while in any other camera
-  Camera does not get confused by Cheese, Pill or Deco Pipes

**Comment by krisk1** [comment]
- Checkpoint in MainArea no longer confuses rat

**Comment by krisk1** [comment]
- Increased Intensity of Spotlights in Level 2 so you can actually see them

**Comment by magnimma** [comment]
- Checkpoint in level 3 fixed
- Enemys fixed
